# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('interest', models.FloatField(default=0.0)),
                ('audience', models.FloatField(default=0.0)),
                ('sentiment', models.FloatField(default=0.0)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Cause')),
            ],
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_date', models.DateTimeField(default=None, null=True)),
                ('action_date', models.DateTimeField(default=None, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagement.Campaign')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.EngagementContent')),
            ],
        ),
        migrations.CreateModel(
            name='EngagementPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='engagement',
            name='purpose',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='engagement.EngagementPurpose'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.Tweet'),
        ),
    ]
